// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceInfo device info
//
// swagger:model DeviceInfo
type DeviceInfo struct {

	// belong
	Belong string `json:"belong,omitempty"`

	// categories
	Categories string `json:"categories,omitempty"`

	// dtype
	Dtype string `json:"dtype,omitempty"`

	// ifmark
	Ifmark string `json:"ifmark,omitempty"`

	// position
	Position string `json:"position,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// time
	Time string `json:"time,omitempty"`

	// username
	Username string `json:"username,omitempty"`

	// yikatong
	Yikatong string `json:"yikatong,omitempty"`
}

// Validate validates this device info
func (m *DeviceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this device info based on context it is used
func (m *DeviceInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceInfo) UnmarshalBinary(b []byte) error {
	var res DeviceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
