// Code generated by go-swagger; DO NOT EDIT.

package qq

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"code.corp.bcollie.net/whistle/lcyutils/models"
)

// PostSendPrivateMsgOKCode is the HTTP code returned for type PostSendPrivateMsgOK
const PostSendPrivateMsgOKCode int = 200

/*PostSendPrivateMsgOK empty response

swagger:response postSendPrivateMsgOK
*/
type PostSendPrivateMsgOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostSendPrivateMsgOK creates PostSendPrivateMsgOK with default headers values
func NewPostSendPrivateMsgOK() *PostSendPrivateMsgOK {

	return &PostSendPrivateMsgOK{}
}

// WithPayload adds the payload to the post send private msg o k response
func (o *PostSendPrivateMsgOK) WithPayload(payload string) *PostSendPrivateMsgOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post send private msg o k response
func (o *PostSendPrivateMsgOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostSendPrivateMsgOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostSendPrivateMsgInternalServerErrorCode is the HTTP code returned for type PostSendPrivateMsgInternalServerError
const PostSendPrivateMsgInternalServerErrorCode int = 500

/*PostSendPrivateMsgInternalServerError internal error

swagger:response postSendPrivateMsgInternalServerError
*/
type PostSendPrivateMsgInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostSendPrivateMsgInternalServerError creates PostSendPrivateMsgInternalServerError with default headers values
func NewPostSendPrivateMsgInternalServerError() *PostSendPrivateMsgInternalServerError {

	return &PostSendPrivateMsgInternalServerError{}
}

// WithPayload adds the payload to the post send private msg internal server error response
func (o *PostSendPrivateMsgInternalServerError) WithPayload(payload *models.APIResponse) *PostSendPrivateMsgInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post send private msg internal server error response
func (o *PostSendPrivateMsgInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostSendPrivateMsgInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
