// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"code.corp.bcollie.net/whistle/lcyutils/restapi/operations/qq"
	"code.corp.bcollie.net/whistle/lcyutils/restapi/operations/shebei"
)

// NewLcyutilsAPI creates a new Lcyutils instance
func NewLcyutilsAPI(spec *loads.Document) *LcyutilsAPI {
	return &LcyutilsAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ShebeiGetGetDeviceHandler: shebei.GetGetDeviceHandlerFunc(func(params shebei.GetGetDeviceParams) middleware.Responder {
			return middleware.NotImplemented("operation shebei.GetGetDevice has not yet been implemented")
		}),
		ShebeiGetGetDeviceListHandler: shebei.GetGetDeviceListHandlerFunc(func(params shebei.GetGetDeviceListParams) middleware.Responder {
			return middleware.NotImplemented("operation shebei.GetGetDeviceList has not yet been implemented")
		}),
		ShebeiGetGetDeviceListFullHandler: shebei.GetGetDeviceListFullHandlerFunc(func(params shebei.GetGetDeviceListFullParams) middleware.Responder {
			return middleware.NotImplemented("operation shebei.GetGetDeviceListFull has not yet been implemented")
		}),
		ShebeiPostModifyDeviceHandler: shebei.PostModifyDeviceHandlerFunc(func(params shebei.PostModifyDeviceParams) middleware.Responder {
			return middleware.NotImplemented("operation shebei.PostModifyDevice has not yet been implemented")
		}),
		ShebeiPostModifyDeviceListHandler: shebei.PostModifyDeviceListHandlerFunc(func(params shebei.PostModifyDeviceListParams) middleware.Responder {
			return middleware.NotImplemented("operation shebei.PostModifyDeviceList has not yet been implemented")
		}),
		QqPostSendPrivateMsgHandler: qq.PostSendPrivateMsgHandlerFunc(func(params qq.PostSendPrivateMsgParams) middleware.Responder {
			return middleware.NotImplemented("operation qq.PostSendPrivateMsg has not yet been implemented")
		}),
	}
}

/*LcyutilsAPI lcyutils */
type LcyutilsAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ShebeiGetGetDeviceHandler sets the operation handler for the get get device operation
	ShebeiGetGetDeviceHandler shebei.GetGetDeviceHandler
	// ShebeiGetGetDeviceListHandler sets the operation handler for the get get device list operation
	ShebeiGetGetDeviceListHandler shebei.GetGetDeviceListHandler
	// ShebeiGetGetDeviceListFullHandler sets the operation handler for the get get device list full operation
	ShebeiGetGetDeviceListFullHandler shebei.GetGetDeviceListFullHandler
	// ShebeiPostModifyDeviceHandler sets the operation handler for the post modify device operation
	ShebeiPostModifyDeviceHandler shebei.PostModifyDeviceHandler
	// ShebeiPostModifyDeviceListHandler sets the operation handler for the post modify device list operation
	ShebeiPostModifyDeviceListHandler shebei.PostModifyDeviceListHandler
	// QqPostSendPrivateMsgHandler sets the operation handler for the post send private msg operation
	QqPostSendPrivateMsgHandler qq.PostSendPrivateMsgHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *LcyutilsAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *LcyutilsAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *LcyutilsAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *LcyutilsAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *LcyutilsAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *LcyutilsAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *LcyutilsAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *LcyutilsAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *LcyutilsAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the LcyutilsAPI
func (o *LcyutilsAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ShebeiGetGetDeviceHandler == nil {
		unregistered = append(unregistered, "shebei.GetGetDeviceHandler")
	}
	if o.ShebeiGetGetDeviceListHandler == nil {
		unregistered = append(unregistered, "shebei.GetGetDeviceListHandler")
	}
	if o.ShebeiGetGetDeviceListFullHandler == nil {
		unregistered = append(unregistered, "shebei.GetGetDeviceListFullHandler")
	}
	if o.ShebeiPostModifyDeviceHandler == nil {
		unregistered = append(unregistered, "shebei.PostModifyDeviceHandler")
	}
	if o.ShebeiPostModifyDeviceListHandler == nil {
		unregistered = append(unregistered, "shebei.PostModifyDeviceListHandler")
	}
	if o.QqPostSendPrivateMsgHandler == nil {
		unregistered = append(unregistered, "qq.PostSendPrivateMsgHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *LcyutilsAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *LcyutilsAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *LcyutilsAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *LcyutilsAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *LcyutilsAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *LcyutilsAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the lcyutils API
func (o *LcyutilsAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *LcyutilsAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/getDevice"] = shebei.NewGetGetDevice(o.context, o.ShebeiGetGetDeviceHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/getDeviceList"] = shebei.NewGetGetDeviceList(o.context, o.ShebeiGetGetDeviceListHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/getDeviceListFull"] = shebei.NewGetGetDeviceListFull(o.context, o.ShebeiGetGetDeviceListFullHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/modifyDevice"] = shebei.NewPostModifyDevice(o.context, o.ShebeiPostModifyDeviceHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/modifyDeviceList"] = shebei.NewPostModifyDeviceList(o.context, o.ShebeiPostModifyDeviceListHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/send_private_msg"] = qq.NewPostSendPrivateMsg(o.context, o.QqPostSendPrivateMsgHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *LcyutilsAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *LcyutilsAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *LcyutilsAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *LcyutilsAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *LcyutilsAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
