// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"code.corp.bcollie.net/whistle/lcyutils/models"
)

// GetGetDeviceOKCode is the HTTP code returned for type GetGetDeviceOK
const GetGetDeviceOKCode int = 200

/*GetGetDeviceOK token check no problem

swagger:response getGetDeviceOK
*/
type GetGetDeviceOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeviceInfo `json:"body,omitempty"`
}

// NewGetGetDeviceOK creates GetGetDeviceOK with default headers values
func NewGetGetDeviceOK() *GetGetDeviceOK {

	return &GetGetDeviceOK{}
}

// WithPayload adds the payload to the get get device o k response
func (o *GetGetDeviceOK) WithPayload(payload *models.DeviceInfo) *GetGetDeviceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get device o k response
func (o *GetGetDeviceOK) SetPayload(payload *models.DeviceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetDeviceInternalServerErrorCode is the HTTP code returned for type GetGetDeviceInternalServerError
const GetGetDeviceInternalServerErrorCode int = 500

/*GetGetDeviceInternalServerError internal error

swagger:response getGetDeviceInternalServerError
*/
type GetGetDeviceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetGetDeviceInternalServerError creates GetGetDeviceInternalServerError with default headers values
func NewGetGetDeviceInternalServerError() *GetGetDeviceInternalServerError {

	return &GetGetDeviceInternalServerError{}
}

// WithPayload adds the payload to the get get device internal server error response
func (o *GetGetDeviceInternalServerError) WithPayload(payload *models.APIResponse) *GetGetDeviceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get device internal server error response
func (o *GetGetDeviceInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetDeviceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
