// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGetDeviceListHandlerFunc turns a function with the right signature into a get get device list handler
type GetGetDeviceListHandlerFunc func(GetGetDeviceListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGetDeviceListHandlerFunc) Handle(params GetGetDeviceListParams) middleware.Responder {
	return fn(params)
}

// GetGetDeviceListHandler interface for that can handle valid get get device list params
type GetGetDeviceListHandler interface {
	Handle(GetGetDeviceListParams) middleware.Responder
}

// NewGetGetDeviceList creates a new http.Handler for the get get device list operation
func NewGetGetDeviceList(ctx *middleware.Context, handler GetGetDeviceListHandler) *GetGetDeviceList {
	return &GetGetDeviceList{Context: ctx, Handler: handler}
}

/* GetGetDeviceList swagger:route GET /getDeviceList shebei getGetDeviceList

device record

*/
type GetGetDeviceList struct {
	Context *middleware.Context
	Handler GetGetDeviceListHandler
}

func (o *GetGetDeviceList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGetDeviceListParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
