// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"code.corp.bcollie.net/whistle/lcyutils/models"
)

// GetGetDeviceListFullOKCode is the HTTP code returned for type GetGetDeviceListFullOK
const GetGetDeviceListFullOKCode int = 200

/*GetGetDeviceListFullOK token check no problem

swagger:response getGetDeviceListFullOK
*/
type GetGetDeviceListFullOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeviceListInfoFull `json:"body,omitempty"`
}

// NewGetGetDeviceListFullOK creates GetGetDeviceListFullOK with default headers values
func NewGetGetDeviceListFullOK() *GetGetDeviceListFullOK {

	return &GetGetDeviceListFullOK{}
}

// WithPayload adds the payload to the get get device list full o k response
func (o *GetGetDeviceListFullOK) WithPayload(payload *models.DeviceListInfoFull) *GetGetDeviceListFullOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get device list full o k response
func (o *GetGetDeviceListFullOK) SetPayload(payload *models.DeviceListInfoFull) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetDeviceListFullOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetDeviceListFullInternalServerErrorCode is the HTTP code returned for type GetGetDeviceListFullInternalServerError
const GetGetDeviceListFullInternalServerErrorCode int = 500

/*GetGetDeviceListFullInternalServerError internal error

swagger:response getGetDeviceListFullInternalServerError
*/
type GetGetDeviceListFullInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetGetDeviceListFullInternalServerError creates GetGetDeviceListFullInternalServerError with default headers values
func NewGetGetDeviceListFullInternalServerError() *GetGetDeviceListFullInternalServerError {

	return &GetGetDeviceListFullInternalServerError{}
}

// WithPayload adds the payload to the get get device list full internal server error response
func (o *GetGetDeviceListFullInternalServerError) WithPayload(payload *models.APIResponse) *GetGetDeviceListFullInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get device list full internal server error response
func (o *GetGetDeviceListFullInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetDeviceListFullInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
