// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostModifyDeviceListParams creates a new PostModifyDeviceListParams object
//
// There are no default values defined in the spec.
func NewPostModifyDeviceListParams() PostModifyDeviceListParams {

	return PostModifyDeviceListParams{}
}

// PostModifyDeviceListParams contains all the bound params for the post modify device list operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostModifyDeviceList
type PostModifyDeviceListParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	Verify string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostModifyDeviceListParams() beforehand.
func (o *PostModifyDeviceListParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qVerify, qhkVerify, _ := qs.GetOK("verify")
	if err := o.bindVerify(qVerify, qhkVerify, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVerify binds and validates parameter Verify from query.
func (o *PostModifyDeviceListParams) bindVerify(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("verify", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("verify", "query", raw); err != nil {
		return err
	}
	o.Verify = raw

	return nil
}
