// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostModifyDeviceHandlerFunc turns a function with the right signature into a post modify device handler
type PostModifyDeviceHandlerFunc func(PostModifyDeviceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostModifyDeviceHandlerFunc) Handle(params PostModifyDeviceParams) middleware.Responder {
	return fn(params)
}

// PostModifyDeviceHandler interface for that can handle valid post modify device params
type PostModifyDeviceHandler interface {
	Handle(PostModifyDeviceParams) middleware.Responder
}

// NewPostModifyDevice creates a new http.Handler for the post modify device operation
func NewPostModifyDevice(ctx *middleware.Context, handler PostModifyDeviceHandler) *PostModifyDevice {
	return &PostModifyDevice{Context: ctx, Handler: handler}
}

/* PostModifyDevice swagger:route POST /modifyDevice shebei postModifyDevice

device record

*/
type PostModifyDevice struct {
	Context *middleware.Context
	Handler PostModifyDeviceHandler
}

func (o *PostModifyDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostModifyDeviceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
