// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostModifyDeviceListHandlerFunc turns a function with the right signature into a post modify device list handler
type PostModifyDeviceListHandlerFunc func(PostModifyDeviceListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostModifyDeviceListHandlerFunc) Handle(params PostModifyDeviceListParams) middleware.Responder {
	return fn(params)
}

// PostModifyDeviceListHandler interface for that can handle valid post modify device list params
type PostModifyDeviceListHandler interface {
	Handle(PostModifyDeviceListParams) middleware.Responder
}

// NewPostModifyDeviceList creates a new http.Handler for the post modify device list operation
func NewPostModifyDeviceList(ctx *middleware.Context, handler PostModifyDeviceListHandler) *PostModifyDeviceList {
	return &PostModifyDeviceList{Context: ctx, Handler: handler}
}

/* PostModifyDeviceList swagger:route POST /modifyDeviceList shebei postModifyDeviceList

device record

*/
type PostModifyDeviceList struct {
	Context *middleware.Context
	Handler PostModifyDeviceListHandler
}

func (o *PostModifyDeviceList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostModifyDeviceListParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
