// Code generated by go-swagger; DO NOT EDIT.

package shebei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"code.corp.bcollie.net/whistle/lcyutils/models"
)

// PostModifyDeviceOKCode is the HTTP code returned for type PostModifyDeviceOK
const PostModifyDeviceOKCode int = 200

/*PostModifyDeviceOK token check no problem

swagger:response postModifyDeviceOK
*/
type PostModifyDeviceOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostModifyDeviceOK creates PostModifyDeviceOK with default headers values
func NewPostModifyDeviceOK() *PostModifyDeviceOK {

	return &PostModifyDeviceOK{}
}

// WithPayload adds the payload to the post modify device o k response
func (o *PostModifyDeviceOK) WithPayload(payload *models.APIResponse) *PostModifyDeviceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post modify device o k response
func (o *PostModifyDeviceOK) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostModifyDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostModifyDeviceInternalServerErrorCode is the HTTP code returned for type PostModifyDeviceInternalServerError
const PostModifyDeviceInternalServerErrorCode int = 500

/*PostModifyDeviceInternalServerError internal error

swagger:response postModifyDeviceInternalServerError
*/
type PostModifyDeviceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostModifyDeviceInternalServerError creates PostModifyDeviceInternalServerError with default headers values
func NewPostModifyDeviceInternalServerError() *PostModifyDeviceInternalServerError {

	return &PostModifyDeviceInternalServerError{}
}

// WithPayload adds the payload to the post modify device internal server error response
func (o *PostModifyDeviceInternalServerError) WithPayload(payload *models.APIResponse) *PostModifyDeviceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post modify device internal server error response
func (o *PostModifyDeviceInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostModifyDeviceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
