// Code generated by go-swagger; DO NOT EDIT.

// Package restapi lcyutils
//
//  lcyutils
//  Schemes:
//    http
//  Host: 106.12.127.2
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
