// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "lcyutils",
    "title": "lcyutils",
    "version": "1.0.0"
  },
  "host": "106.12.127.2",
  "basePath": "/",
  "paths": {
    "/getDevice": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/DeviceInfo"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/getDeviceList": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/DeviceListInfo"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/getDeviceListFull": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/DeviceListInfoFull"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/modifyDevice": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "categorie",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "dtype",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "time",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "belong",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "status",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "username",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "yikatong",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "position",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "ifmark",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "verify",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/modifyDeviceList": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "parameters": [
          {
            "type": "string",
            "name": "verify",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/send_private_msg": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "qq"
        ],
        "summary": "private message",
        "parameters": [
          {
            "type": "string",
            "description": "QQ number",
            "name": "user_id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "message",
            "name": "message",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "empty response",
            "schema": {
              "type": "string",
              "example": "I am the token and I am here waiting for you! My lele!"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "DeviceInfo": {
      "type": "object",
      "properties": {
        "belong": {
          "type": "string"
        },
        "categories": {
          "type": "string"
        },
        "dtype": {
          "type": "string"
        },
        "ifmark": {
          "type": "string"
        },
        "position": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "time": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "yikatong": {
          "type": "string"
        }
      }
    },
    "DeviceListInfo": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "sn_code": {
                "type": "string"
              },
              "status": {
                "type": "string"
              },
              "type": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "DeviceListInfoFull": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "belong": {
                "type": "string"
              },
              "buytime": {
                "type": "string"
              },
              "categories": {
                "type": "string"
              },
              "id": {
                "type": "string"
              },
              "ifmark": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "position": {
                "type": "string"
              },
              "sn_code": {
                "type": "string"
              },
              "status": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "yikatong": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "Overview information",
      "name": "overview"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "lcyutils",
    "title": "lcyutils",
    "version": "1.0.0"
  },
  "host": "106.12.127.2",
  "basePath": "/",
  "paths": {
    "/getDevice": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/DeviceInfo"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/getDeviceList": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/DeviceListInfo"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/getDeviceListFull": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/DeviceListInfoFull"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/modifyDevice": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "categorie",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "dtype",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "time",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "belong",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "status",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "username",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "yikatong",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "position",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "ifmark",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "verify",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/modifyDeviceList": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "shebei"
        ],
        "summary": "device record",
        "parameters": [
          {
            "type": "string",
            "name": "verify",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "token check no problem",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/send_private_msg": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "qq"
        ],
        "summary": "private message",
        "parameters": [
          {
            "type": "string",
            "description": "QQ number",
            "name": "user_id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "message",
            "name": "message",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "empty response",
            "schema": {
              "type": "string",
              "example": "I am the token and I am here waiting for you! My lele!"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "DeviceInfo": {
      "type": "object",
      "properties": {
        "belong": {
          "type": "string"
        },
        "categories": {
          "type": "string"
        },
        "dtype": {
          "type": "string"
        },
        "ifmark": {
          "type": "string"
        },
        "position": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "time": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "yikatong": {
          "type": "string"
        }
      }
    },
    "DeviceListInfo": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DeviceListInfoDataItems0"
          }
        }
      }
    },
    "DeviceListInfoDataItems0": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "sn_code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "DeviceListInfoFull": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DeviceListInfoFullDataItems0"
          }
        }
      }
    },
    "DeviceListInfoFullDataItems0": {
      "type": "object",
      "properties": {
        "belong": {
          "type": "string"
        },
        "buytime": {
          "type": "string"
        },
        "categories": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "ifmark": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "position": {
          "type": "string"
        },
        "sn_code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "yikatong": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Overview information",
      "name": "overview"
    }
  ]
}`))
}
